version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam
        auth:
          username: nuscrbot
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v3-{{ checksum "nuscr.opam" }}
            - deps-v3-

      - run:
          name: Install m4 and z3
          command: |
            sudo apt-get update
            sudo apt-get install m4 z3 python2.7 libgmp-dev -y

      - run:
          name: Pin packages
          command: |
            opam pin add --no-action -y nuscr.dev -k path .
            opam pin add --no-action -y nuscr-web.dev -k path .

      - run:
          name: Install dependencies
          command: opam install -dt . --deps-only

      - run:
          name: Build
          command: |
            eval $(opam config env)
            dune build

      - run:
          name: Test
          command: |
            eval $(opam config env)
            dune runtest

      - run:
          name: Build web version
          command: |
            eval $(opam config env)
            WHERE=../docs make -C web deploy

      - run:
          name: Build docs
          command: |
            eval $(opam config env)
            dune build @doc
            mkdir -p docs/docs
            cp -r _build/default/_doc/_html/* docs/docs

      - run:
          name: Check format
          command: |
            opam install ocamlformat
            eval $(opam config env)
            dune build @fmt

      - persist_to_workspace:
          root: .
          paths:
            - docs

      - save_cache:
          key: deps-v3-{{ checksum "nuscr.opam" }}
          paths:
            - ~/.opam

  docs-deploy:
    docker:
      - image: node:14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@3.2.3
            git config user.email "nuscr@nuscr.dev"
            git config user.name "NuScr"
      - add_ssh_keys:
          fingerprints:
            - "d7:04:a2:2e:53:da:b4:f7:22:fe:66:57:a1:f1:ef:c9"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs --dotfiles --message "[skip ci] change" -f
          environment:
            CACHE_DIR: "~/.cache"

  build-docker-image:
    docker:
      - image: circleci/buildpack-deps
        auth:
          username: nuscrbot
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Docker image
          command: |
            docker build . -t nuscr/nuscr:latest
            docker run nuscr/nuscr:latest nuscr --version

      - run:
          name: Push Docker image
          command: |
            docker login -u nuscrbot -p $DOCKERHUB_PASSWORD
            docker push nuscr/nuscr:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds
      - build-docker-image:
          context:
            - docker-hub-creds
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
